// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow_plugin_compute_core/protocol/v1/bootstrap.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signature-free, domain-bound bytes for the ephemeral install receipt key.
type AgentSetupInstallReceiptPayload struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Domain              string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ProtocolVersion     string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ReceiptId           string                 `protobuf:"bytes,3,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	Challenge           string                 `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	InviteId            string                 `protobuf:"bytes,5,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InstallSessionId    string                 `protobuf:"bytes,6,opt,name=install_session_id,json=installSessionId,proto3" json:"install_session_id,omitempty"`
	WorkerId            string                 `protobuf:"bytes,7,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	PackageId           string                 `protobuf:"bytes,8,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackageVersion      string                 `protobuf:"bytes,9,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	PackageDigest       string                 `protobuf:"bytes,10,opt,name=package_digest,json=packageDigest,proto3" json:"package_digest,omitempty"`
	ManifestDigest      string                 `protobuf:"bytes,11,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	BootstrapEpoch      uint64                 `protobuf:"varint,12,opt,name=bootstrap_epoch,json=bootstrapEpoch,proto3" json:"bootstrap_epoch,omitempty"`
	PackageEpoch        uint64                 `protobuf:"varint,13,opt,name=package_epoch,json=packageEpoch,proto3" json:"package_epoch,omitempty"`
	KeysetEpoch         uint64                 `protobuf:"varint,14,opt,name=keyset_epoch,json=keysetEpoch,proto3" json:"keyset_epoch,omitempty"`
	LauncherDigest      string                 `protobuf:"bytes,15,opt,name=launcher_digest,json=launcherDigest,proto3" json:"launcher_digest,omitempty"`
	SlotId              string                 `protobuf:"bytes,16,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SlotDigest          string                 `protobuf:"bytes,17,opt,name=slot_digest,json=slotDigest,proto3" json:"slot_digest,omitempty"`
	ServiceUnitDigest   string                 `protobuf:"bytes,18,opt,name=service_unit_digest,json=serviceUnitDigest,proto3" json:"service_unit_digest,omitempty"`
	ServiceMode         string                 `protobuf:"bytes,19,opt,name=service_mode,json=serviceMode,proto3" json:"service_mode,omitempty"`
	StartedPid          int64                  `protobuf:"varint,20,opt,name=started_pid,json=startedPid,proto3" json:"started_pid,omitempty"`
	HeartbeatId         string                 `protobuf:"bytes,21,opt,name=heartbeat_id,json=heartbeatId,proto3" json:"heartbeat_id,omitempty"`
	HeartbeatAtUnixNano int64                  `protobuf:"varint,22,opt,name=heartbeat_at_unix_nano,json=heartbeatAtUnixNano,proto3" json:"heartbeat_at_unix_nano,omitempty"`
	CloudFinalUnit      string                 `protobuf:"bytes,23,opt,name=cloud_final_unit,json=cloudFinalUnit,proto3" json:"cloud_final_unit,omitempty"`
	ScrubUnit           string                 `protobuf:"bytes,24,opt,name=scrub_unit,json=scrubUnit,proto3" json:"scrub_unit,omitempty"`
	WrapperHash         string                 `protobuf:"bytes,25,opt,name=wrapper_hash,json=wrapperHash,proto3" json:"wrapper_hash,omitempty"`
	ScanHitCount        uint64                 `protobuf:"varint,26,opt,name=scan_hit_count,json=scanHitCount,proto3" json:"scan_hit_count,omitempty"`
	CodeDigest          string                 `protobuf:"bytes,27,opt,name=code_digest,json=codeDigest,proto3" json:"code_digest,omitempty"`
	CompletedAtUnixNano int64                  `protobuf:"varint,28,opt,name=completed_at_unix_nano,json=completedAtUnixNano,proto3" json:"completed_at_unix_nano,omitempty"`
	ExpiresAtUnixNano   int64                  `protobuf:"varint,29,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentSetupInstallReceiptPayload) Reset() {
	*x = AgentSetupInstallReceiptPayload{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSetupInstallReceiptPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSetupInstallReceiptPayload) ProtoMessage() {}

func (x *AgentSetupInstallReceiptPayload) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSetupInstallReceiptPayload.ProtoReflect.Descriptor instead.
func (*AgentSetupInstallReceiptPayload) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSetupInstallReceiptPayload) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetInstallSessionId() string {
	if x != nil {
		return x.InstallSessionId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetPackageDigest() string {
	if x != nil {
		return x.PackageDigest
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetBootstrapEpoch() uint64 {
	if x != nil {
		return x.BootstrapEpoch
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetPackageEpoch() uint64 {
	if x != nil {
		return x.PackageEpoch
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetKeysetEpoch() uint64 {
	if x != nil {
		return x.KeysetEpoch
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetLauncherDigest() string {
	if x != nil {
		return x.LauncherDigest
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetSlotDigest() string {
	if x != nil {
		return x.SlotDigest
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetServiceUnitDigest() string {
	if x != nil {
		return x.ServiceUnitDigest
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetServiceMode() string {
	if x != nil {
		return x.ServiceMode
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetStartedPid() int64 {
	if x != nil {
		return x.StartedPid
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetHeartbeatId() string {
	if x != nil {
		return x.HeartbeatId
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetHeartbeatAtUnixNano() int64 {
	if x != nil {
		return x.HeartbeatAtUnixNano
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetCloudFinalUnit() string {
	if x != nil {
		return x.CloudFinalUnit
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetScrubUnit() string {
	if x != nil {
		return x.ScrubUnit
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetWrapperHash() string {
	if x != nil {
		return x.WrapperHash
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetScanHitCount() uint64 {
	if x != nil {
		return x.ScanHitCount
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetCodeDigest() string {
	if x != nil {
		return x.CodeDigest
	}
	return ""
}

func (x *AgentSetupInstallReceiptPayload) GetCompletedAtUnixNano() int64 {
	if x != nil {
		return x.CompletedAtUnixNano
	}
	return 0
}

func (x *AgentSetupInstallReceiptPayload) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

var File_workflow_plugin_compute_core_protocol_v1_bootstrap_proto protoreflect.FileDescriptor

const file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDesc = "" +
	"\n" +
	"8workflow_plugin_compute_core/protocol/v1/bootstrap.proto\x12(workflow_plugin_compute_core.protocol.v1\"\xda\b\n" +
	"\x1fAgentSetupInstallReceiptPayload\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x03 \x01(\tR\treceiptId\x12\x1c\n" +
	"\tchallenge\x18\x04 \x01(\tR\tchallenge\x12\x1b\n" +
	"\tinvite_id\x18\x05 \x01(\tR\binviteId\x12,\n" +
	"\x12install_session_id\x18\x06 \x01(\tR\x10installSessionId\x12\x1b\n" +
	"\tworker_id\x18\a \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"package_id\x18\b \x01(\tR\tpackageId\x12'\n" +
	"\x0fpackage_version\x18\t \x01(\tR\x0epackageVersion\x12%\n" +
	"\x0epackage_digest\x18\n" +
	" \x01(\tR\rpackageDigest\x12'\n" +
	"\x0fmanifest_digest\x18\v \x01(\tR\x0emanifestDigest\x12'\n" +
	"\x0fbootstrap_epoch\x18\f \x01(\x04R\x0ebootstrapEpoch\x12#\n" +
	"\rpackage_epoch\x18\r \x01(\x04R\fpackageEpoch\x12!\n" +
	"\fkeyset_epoch\x18\x0e \x01(\x04R\vkeysetEpoch\x12'\n" +
	"\x0flauncher_digest\x18\x0f \x01(\tR\x0elauncherDigest\x12\x17\n" +
	"\aslot_id\x18\x10 \x01(\tR\x06slotId\x12\x1f\n" +
	"\vslot_digest\x18\x11 \x01(\tR\n" +
	"slotDigest\x12.\n" +
	"\x13service_unit_digest\x18\x12 \x01(\tR\x11serviceUnitDigest\x12!\n" +
	"\fservice_mode\x18\x13 \x01(\tR\vserviceMode\x12\x1f\n" +
	"\vstarted_pid\x18\x14 \x01(\x03R\n" +
	"startedPid\x12!\n" +
	"\fheartbeat_id\x18\x15 \x01(\tR\vheartbeatId\x123\n" +
	"\x16heartbeat_at_unix_nano\x18\x16 \x01(\x03R\x13heartbeatAtUnixNano\x12(\n" +
	"\x10cloud_final_unit\x18\x17 \x01(\tR\x0ecloudFinalUnit\x12\x1d\n" +
	"\n" +
	"scrub_unit\x18\x18 \x01(\tR\tscrubUnit\x12!\n" +
	"\fwrapper_hash\x18\x19 \x01(\tR\vwrapperHash\x12$\n" +
	"\x0escan_hit_count\x18\x1a \x01(\x04R\fscanHitCount\x12\x1f\n" +
	"\vcode_digest\x18\x1b \x01(\tR\n" +
	"codeDigest\x123\n" +
	"\x16completed_at_unix_nano\x18\x1c \x01(\x03R\x13completedAtUnixNano\x12/\n" +
	"\x14expires_at_unix_nano\x18\x1d \x01(\x03R\x11expiresAtUnixNanoBDZBgithub.com/GoCodeAlone/workflow-plugin-compute-core/protocol/pb;pbb\x06proto3"

var (
	file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescOnce sync.Once
	file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescData []byte
)

func file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescGZIP() []byte {
	file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescOnce.Do(func() {
		file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDesc), len(file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDesc)))
	})
	return file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDescData
}

var file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_goTypes = []any{
	(*AgentSetupInstallReceiptPayload)(nil), // 0: workflow_plugin_compute_core.protocol.v1.AgentSetupInstallReceiptPayload
}
var file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_init() }
func file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_init() {
	if File_workflow_plugin_compute_core_protocol_v1_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDesc), len(file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_goTypes,
		DependencyIndexes: file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_depIdxs,
		MessageInfos:      file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_msgTypes,
	}.Build()
	File_workflow_plugin_compute_core_protocol_v1_bootstrap_proto = out.File
	file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_goTypes = nil
	file_workflow_plugin_compute_core_protocol_v1_bootstrap_proto_depIdxs = nil
}
