// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow_plugin_compute_core/protocol/v1/network_audit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkAuditRecord struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	ProtocolVersion    string                        `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RecordId           string                        `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	TaskId             string                        `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId            string                        `protobuf:"bytes,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	WorkerId           string                        `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Provider           *NetworkAuditProviderEvidence `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	Destination        *NetworkAuditDestination      `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	ResourceUsage      *NetworkAuditResourceUsage    `protobuf:"bytes,8,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	Labels             map[string]string             `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartedAtUnixNano  int64                         `protobuf:"varint,10,opt,name=started_at_unix_nano,json=startedAtUnixNano,proto3" json:"started_at_unix_nano,omitempty"`
	FinishedAtUnixNano int64                         `protobuf:"varint,11,opt,name=finished_at_unix_nano,json=finishedAtUnixNano,proto3" json:"finished_at_unix_nano,omitempty"`
	ObservedAtUnixNano int64                         `protobuf:"varint,12,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkAuditRecord) Reset() {
	*x = NetworkAuditRecord{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAuditRecord) ProtoMessage() {}

func (x *NetworkAuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAuditRecord.ProtoReflect.Descriptor instead.
func (*NetworkAuditRecord) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkAuditRecord) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *NetworkAuditRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *NetworkAuditRecord) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NetworkAuditRecord) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *NetworkAuditRecord) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *NetworkAuditRecord) GetProvider() *NetworkAuditProviderEvidence {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *NetworkAuditRecord) GetDestination() *NetworkAuditDestination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *NetworkAuditRecord) GetResourceUsage() *NetworkAuditResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *NetworkAuditRecord) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NetworkAuditRecord) GetStartedAtUnixNano() int64 {
	if x != nil {
		return x.StartedAtUnixNano
	}
	return 0
}

func (x *NetworkAuditRecord) GetFinishedAtUnixNano() int64 {
	if x != nil {
		return x.FinishedAtUnixNano
	}
	return 0
}

func (x *NetworkAuditRecord) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

type NetworkAuditProviderEvidence struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProviderId       string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	PluginName       string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginVersion    string                 `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	ContractId       string                 `protobuf:"bytes,4,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	ContractVersion  string                 `protobuf:"bytes,5,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	DescriptorDigest string                 `protobuf:"bytes,6,opt,name=descriptor_digest,json=descriptorDigest,proto3" json:"descriptor_digest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkAuditProviderEvidence) Reset() {
	*x = NetworkAuditProviderEvidence{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAuditProviderEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAuditProviderEvidence) ProtoMessage() {}

func (x *NetworkAuditProviderEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAuditProviderEvidence.ProtoReflect.Descriptor instead.
func (*NetworkAuditProviderEvidence) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkAuditProviderEvidence) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *NetworkAuditProviderEvidence) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *NetworkAuditProviderEvidence) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *NetworkAuditProviderEvidence) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NetworkAuditProviderEvidence) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *NetworkAuditProviderEvidence) GetDescriptorDigest() string {
	if x != nil {
		return x.DescriptorDigest
	}
	return ""
}

type NetworkAuditDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAuditDestination) Reset() {
	*x = NetworkAuditDestination{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAuditDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAuditDestination) ProtoMessage() {}

func (x *NetworkAuditDestination) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAuditDestination.ProtoReflect.Descriptor instead.
func (*NetworkAuditDestination) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkAuditDestination) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NetworkAuditDestination) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NetworkAuditResourceUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuMillis      int64                  `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	GpuMillis      int64                  `protobuf:"varint,2,opt,name=gpu_millis,json=gpuMillis,proto3" json:"gpu_millis,omitempty"`
	MaxMemoryBytes int64                  `protobuf:"varint,3,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	NetworkRxBytes int64                  `protobuf:"varint,4,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes int64                  `protobuf:"varint,5,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	WorkspaceBytes int64                  `protobuf:"varint,6,opt,name=workspace_bytes,json=workspaceBytes,proto3" json:"workspace_bytes,omitempty"`
	OutputBytes    int64                  `protobuf:"varint,7,opt,name=output_bytes,json=outputBytes,proto3" json:"output_bytes,omitempty"`
	LimitHit       string                 `protobuf:"bytes,8,opt,name=limit_hit,json=limitHit,proto3" json:"limit_hit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkAuditResourceUsage) Reset() {
	*x = NetworkAuditResourceUsage{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAuditResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAuditResourceUsage) ProtoMessage() {}

func (x *NetworkAuditResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAuditResourceUsage.ProtoReflect.Descriptor instead.
func (*NetworkAuditResourceUsage) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkAuditResourceUsage) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetGpuMillis() int64 {
	if x != nil {
		return x.GpuMillis
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetMaxMemoryBytes() int64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetNetworkRxBytes() int64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetNetworkTxBytes() int64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetWorkspaceBytes() int64 {
	if x != nil {
		return x.WorkspaceBytes
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetOutputBytes() int64 {
	if x != nil {
		return x.OutputBytes
	}
	return 0
}

func (x *NetworkAuditResourceUsage) GetLimitHit() string {
	if x != nil {
		return x.LimitHit
	}
	return ""
}

type NetworkAuditValidationIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAuditValidationIssue) Reset() {
	*x = NetworkAuditValidationIssue{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAuditValidationIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAuditValidationIssue) ProtoMessage() {}

func (x *NetworkAuditValidationIssue) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAuditValidationIssue.ProtoReflect.Descriptor instead.
func (*NetworkAuditValidationIssue) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkAuditValidationIssue) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NetworkAuditValidationIssue) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *NetworkAuditValidationIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workflow_plugin_compute_core_protocol_v1_network_audit_proto protoreflect.FileDescriptor

const file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDesc = "" +
	"\n" +
	"<workflow_plugin_compute_core/protocol/v1/network_audit.proto\x12(workflow_plugin_compute_core.protocol.v1\"\x96\x06\n" +
	"\x12NetworkAuditRecord\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\x12b\n" +
	"\bprovider\x18\x06 \x01(\v2F.workflow_plugin_compute_core.protocol.v1.NetworkAuditProviderEvidenceR\bprovider\x12c\n" +
	"\vdestination\x18\a \x01(\v2A.workflow_plugin_compute_core.protocol.v1.NetworkAuditDestinationR\vdestination\x12j\n" +
	"\x0eresource_usage\x18\b \x01(\v2C.workflow_plugin_compute_core.protocol.v1.NetworkAuditResourceUsageR\rresourceUsage\x12`\n" +
	"\x06labels\x18\t \x03(\v2H.workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.LabelsEntryR\x06labels\x12/\n" +
	"\x14started_at_unix_nano\x18\n" +
	" \x01(\x03R\x11startedAtUnixNano\x121\n" +
	"\x15finished_at_unix_nano\x18\v \x01(\x03R\x12finishedAtUnixNano\x121\n" +
	"\x15observed_at_unix_nano\x18\f \x01(\x03R\x12observedAtUnixNano\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\x1cNetworkAuditProviderEvidence\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12\x1f\n" +
	"\vcontract_id\x18\x04 \x01(\tR\n" +
	"contractId\x12)\n" +
	"\x10contract_version\x18\x05 \x01(\tR\x0fcontractVersion\x12+\n" +
	"\x11descriptor_digest\x18\x06 \x01(\tR\x10descriptorDigest\"C\n" +
	"\x17NetworkAuditDestination\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc0\x02\n" +
	"\x19NetworkAuditResourceUsage\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\x03R\tcpuMillis\x12\x1d\n" +
	"\n" +
	"gpu_millis\x18\x02 \x01(\x03R\tgpuMillis\x12(\n" +
	"\x10max_memory_bytes\x18\x03 \x01(\x03R\x0emaxMemoryBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x04 \x01(\x03R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x05 \x01(\x03R\x0enetworkTxBytes\x12'\n" +
	"\x0fworkspace_bytes\x18\x06 \x01(\x03R\x0eworkspaceBytes\x12!\n" +
	"\foutput_bytes\x18\a \x01(\x03R\voutputBytes\x12\x1b\n" +
	"\tlimit_hit\x18\b \x01(\tR\blimitHit\"a\n" +
	"\x1bNetworkAuditValidationIssue\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageBDZBgithub.com/GoCodeAlone/workflow-plugin-compute-core/protocol/pb;pbb\x06proto3"

var (
	file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescOnce sync.Once
	file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescData []byte
)

func file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescGZIP() []byte {
	file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescOnce.Do(func() {
		file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDesc), len(file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDesc)))
	})
	return file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDescData
}

var file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_goTypes = []any{
	(*NetworkAuditRecord)(nil),           // 0: workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord
	(*NetworkAuditProviderEvidence)(nil), // 1: workflow_plugin_compute_core.protocol.v1.NetworkAuditProviderEvidence
	(*NetworkAuditDestination)(nil),      // 2: workflow_plugin_compute_core.protocol.v1.NetworkAuditDestination
	(*NetworkAuditResourceUsage)(nil),    // 3: workflow_plugin_compute_core.protocol.v1.NetworkAuditResourceUsage
	(*NetworkAuditValidationIssue)(nil),  // 4: workflow_plugin_compute_core.protocol.v1.NetworkAuditValidationIssue
	nil,                                  // 5: workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.LabelsEntry
}
var file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_depIdxs = []int32{
	1, // 0: workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.provider:type_name -> workflow_plugin_compute_core.protocol.v1.NetworkAuditProviderEvidence
	2, // 1: workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.destination:type_name -> workflow_plugin_compute_core.protocol.v1.NetworkAuditDestination
	3, // 2: workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.resource_usage:type_name -> workflow_plugin_compute_core.protocol.v1.NetworkAuditResourceUsage
	5, // 3: workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.labels:type_name -> workflow_plugin_compute_core.protocol.v1.NetworkAuditRecord.LabelsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_init() }
func file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_init() {
	if File_workflow_plugin_compute_core_protocol_v1_network_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDesc), len(file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_goTypes,
		DependencyIndexes: file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_depIdxs,
		MessageInfos:      file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_msgTypes,
	}.Build()
	File_workflow_plugin_compute_core_protocol_v1_network_audit_proto = out.File
	file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_goTypes = nil
	file_workflow_plugin_compute_core_protocol_v1_network_audit_proto_depIdxs = nil
}
