// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow_plugin_compute_core/protocol/v1/runtime_provider.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DescribeRequest asks the provider to describe its capabilities.
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{0}
}

// ProviderCapabilities describes what a RuntimeProvider can handle.
type ProviderCapabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProviderId        string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	WorkloadKinds     []string               `protobuf:"bytes,2,rep,name=workload_kinds,json=workloadKinds,proto3" json:"workload_kinds,omitempty"`
	ExecutorProviders []string               `protobuf:"bytes,3,rep,name=executor_providers,json=executorProviders,proto3" json:"executor_providers,omitempty"`
	RuntimeProfiles   []string               `protobuf:"bytes,4,rep,name=runtime_profiles,json=runtimeProfiles,proto3" json:"runtime_profiles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProviderCapabilities) Reset() {
	*x = ProviderCapabilities{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCapabilities) ProtoMessage() {}

func (x *ProviderCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCapabilities.ProtoReflect.Descriptor instead.
func (*ProviderCapabilities) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderCapabilities) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderCapabilities) GetWorkloadKinds() []string {
	if x != nil {
		return x.WorkloadKinds
	}
	return nil
}

func (x *ProviderCapabilities) GetExecutorProviders() []string {
	if x != nil {
		return x.ExecutorProviders
	}
	return nil
}

func (x *ProviderCapabilities) GetRuntimeProfiles() []string {
	if x != nil {
		return x.RuntimeProfiles
	}
	return nil
}

// RunRequest initiates a one-shot workload execution.
// env values may be unresolved secret:// refs — the provider resolves them.
type RunRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutorProvider string                 `protobuf:"bytes,1,opt,name=executor_provider,json=executorProvider,proto3" json:"executor_provider,omitempty"`
	Input            []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Env              map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TaskId           string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId          string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetExecutorProvider() string {
	if x != nil {
		return x.ExecutorProvider
	}
	return ""
}

func (x *RunRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// RunEvent is a streaming chunk emitted during RunRequest execution.
type RunEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunEvent_Stdout
	//	*RunEvent_Stderr
	//	*RunEvent_Terminal
	Event         isRunEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{3}
}

func (x *RunEvent) GetEvent() isRunEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunEvent) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *RunEvent) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *RunEvent) GetTerminal() *RunResult {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Terminal); ok {
			return x.Terminal
		}
	}
	return nil
}

type isRunEvent_Event interface {
	isRunEvent_Event()
}

type RunEvent_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type RunEvent_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type RunEvent_Terminal struct {
	Terminal *RunResult `protobuf:"bytes,3,opt,name=terminal,proto3,oneof"`
}

func (*RunEvent_Stdout) isRunEvent_Event() {}

func (*RunEvent_Stderr) isRunEvent_Event() {}

func (*RunEvent_Terminal) isRunEvent_Event() {}

// RunResult is the terminal outcome of a RunRequest.
type RunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ArtifactHash  string                 `protobuf:"bytes,2,opt,name=artifact_hash,json=artifactHash,proto3" json:"artifact_hash,omitempty"`
	Artifacts     []string               `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResult) Reset() {
	*x = RunResult{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResult) ProtoMessage() {}

func (x *RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResult.ProtoReflect.Descriptor instead.
func (*RunResult) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{4}
}

func (x *RunResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunResult) GetArtifactHash() string {
	if x != nil {
		return x.ArtifactHash
	}
	return ""
}

func (x *RunResult) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// StartSessionRequest initiates a long-lived session.
// env values may be unresolved secret:// refs — the provider resolves them.
type StartSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutorProvider string                 `protobuf:"bytes,1,opt,name=executor_provider,json=executorProvider,proto3" json:"executor_provider,omitempty"`
	Input            []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Env              map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TaskId           string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId          string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{5}
}

func (x *StartSessionRequest) GetExecutorProvider() string {
	if x != nil {
		return x.ExecutorProvider
	}
	return ""
}

func (x *StartSessionRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartSessionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartSessionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartSessionRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// SessionHandle identifies a running session.
type SessionHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHandle) Reset() {
	*x = SessionHandle{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHandle) ProtoMessage() {}

func (x *SessionHandle) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHandle.ProtoReflect.Descriptor instead.
func (*SessionHandle) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{6}
}

func (x *SessionHandle) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// SessionEvent is an event emitted by a running session.
// evidence is unsigned — the host signs it later.
type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Evidence      []byte                 `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	TsUnixNanos   int64                  `protobuf:"varint,3,opt,name=ts_unix_nanos,json=tsUnixNanos,proto3" json:"ts_unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{7}
}

func (x *SessionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SessionEvent) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *SessionEvent) GetTsUnixNanos() int64 {
	if x != nil {
		return x.TsUnixNanos
	}
	return 0
}

// ControlSessionRequest sends a control action to a running session.
// action examples: health, renew, stop, mutate.
type ControlSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlSessionRequest) Reset() {
	*x = ControlSessionRequest{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlSessionRequest) ProtoMessage() {}

func (x *ControlSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlSessionRequest.ProtoReflect.Descriptor instead.
func (*ControlSessionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ControlSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlSessionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ControlSessionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ControlSessionResponse is the reply to a ControlSessionRequest.
type ControlSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlSessionResponse) Reset() {
	*x = ControlSessionResponse{}
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlSessionResponse) ProtoMessage() {}

func (x *ControlSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlSessionResponse.ProtoReflect.Descriptor instead.
func (*ControlSessionResponse) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ControlSessionResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ControlSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto protoreflect.FileDescriptor

const file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDesc = "" +
	"\n" +
	"?workflow_plugin_compute_core/protocol/v1/runtime_provider.proto\x12(workflow_plugin_compute_core.protocol.v1\"\x11\n" +
	"\x0fDescribeRequest\"\xb8\x01\n" +
	"\x14ProviderCapabilities\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12%\n" +
	"\x0eworkload_kinds\x18\x02 \x03(\tR\rworkloadKinds\x12-\n" +
	"\x12executor_providers\x18\x03 \x03(\tR\x11executorProviders\x12)\n" +
	"\x10runtime_profiles\x18\x04 \x03(\tR\x0fruntimeProfiles\"\x8c\x02\n" +
	"\n" +
	"RunRequest\x12+\n" +
	"\x11executor_provider\x18\x01 \x01(\tR\x10executorProvider\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12O\n" +
	"\x03env\x18\x03 \x03(\v2=.workflow_plugin_compute_core.protocol.v1.RunRequest.EnvEntryR\x03env\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\bRunEvent\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12Q\n" +
	"\bterminal\x18\x03 \x01(\v23.workflow_plugin_compute_core.protocol.v1.RunResultH\x00R\bterminalB\a\n" +
	"\x05event\"k\n" +
	"\tRunResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12#\n" +
	"\rartifact_hash\x18\x02 \x01(\tR\fartifactHash\x12\x1c\n" +
	"\tartifacts\x18\x03 \x03(\tR\tartifacts\"\x9e\x02\n" +
	"\x13StartSessionRequest\x12+\n" +
	"\x11executor_provider\x18\x01 \x01(\tR\x10executorProvider\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12X\n" +
	"\x03env\x18\x03 \x03(\v2F.workflow_plugin_compute_core.protocol.v1.StartSessionRequest.EnvEntryR\x03env\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\rSessionHandle\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"m\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1a\n" +
	"\bevidence\x18\x02 \x01(\fR\bevidence\x12\"\n" +
	"\rts_unix_nanos\x18\x03 \x01(\x03R\vtsUnixNanos\"h\n" +
	"\x15ControlSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"L\n" +
	"\x16ControlSessionResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb7\x05\n" +
	"\x16RuntimeProviderService\x12\x85\x01\n" +
	"\bDescribe\x129.workflow_plugin_compute_core.protocol.v1.DescribeRequest\x1a>.workflow_plugin_compute_core.protocol.v1.ProviderCapabilities\x12q\n" +
	"\x03Run\x124.workflow_plugin_compute_core.protocol.v1.RunRequest\x1a2.workflow_plugin_compute_core.protocol.v1.RunEvent0\x01\x12\x86\x01\n" +
	"\fStartSession\x12=.workflow_plugin_compute_core.protocol.v1.StartSessionRequest\x1a7.workflow_plugin_compute_core.protocol.v1.SessionHandle\x12\x82\x01\n" +
	"\rSessionEvents\x127.workflow_plugin_compute_core.protocol.v1.SessionHandle\x1a6.workflow_plugin_compute_core.protocol.v1.SessionEvent0\x01\x12\x93\x01\n" +
	"\x0eControlSession\x12?.workflow_plugin_compute_core.protocol.v1.ControlSessionRequest\x1a@.workflow_plugin_compute_core.protocol.v1.ControlSessionResponseBDZBgithub.com/GoCodeAlone/workflow-plugin-compute-core/protocol/pb;pbb\x06proto3"

var (
	file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescOnce sync.Once
	file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescData []byte
)

func file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescGZIP() []byte {
	file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescOnce.Do(func() {
		file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDesc), len(file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDesc)))
	})
	return file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDescData
}

var file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_goTypes = []any{
	(*DescribeRequest)(nil),        // 0: workflow_plugin_compute_core.protocol.v1.DescribeRequest
	(*ProviderCapabilities)(nil),   // 1: workflow_plugin_compute_core.protocol.v1.ProviderCapabilities
	(*RunRequest)(nil),             // 2: workflow_plugin_compute_core.protocol.v1.RunRequest
	(*RunEvent)(nil),               // 3: workflow_plugin_compute_core.protocol.v1.RunEvent
	(*RunResult)(nil),              // 4: workflow_plugin_compute_core.protocol.v1.RunResult
	(*StartSessionRequest)(nil),    // 5: workflow_plugin_compute_core.protocol.v1.StartSessionRequest
	(*SessionHandle)(nil),          // 6: workflow_plugin_compute_core.protocol.v1.SessionHandle
	(*SessionEvent)(nil),           // 7: workflow_plugin_compute_core.protocol.v1.SessionEvent
	(*ControlSessionRequest)(nil),  // 8: workflow_plugin_compute_core.protocol.v1.ControlSessionRequest
	(*ControlSessionResponse)(nil), // 9: workflow_plugin_compute_core.protocol.v1.ControlSessionResponse
	nil,                            // 10: workflow_plugin_compute_core.protocol.v1.RunRequest.EnvEntry
	nil,                            // 11: workflow_plugin_compute_core.protocol.v1.StartSessionRequest.EnvEntry
}
var file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_depIdxs = []int32{
	10, // 0: workflow_plugin_compute_core.protocol.v1.RunRequest.env:type_name -> workflow_plugin_compute_core.protocol.v1.RunRequest.EnvEntry
	4,  // 1: workflow_plugin_compute_core.protocol.v1.RunEvent.terminal:type_name -> workflow_plugin_compute_core.protocol.v1.RunResult
	11, // 2: workflow_plugin_compute_core.protocol.v1.StartSessionRequest.env:type_name -> workflow_plugin_compute_core.protocol.v1.StartSessionRequest.EnvEntry
	0,  // 3: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.Describe:input_type -> workflow_plugin_compute_core.protocol.v1.DescribeRequest
	2,  // 4: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.Run:input_type -> workflow_plugin_compute_core.protocol.v1.RunRequest
	5,  // 5: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.StartSession:input_type -> workflow_plugin_compute_core.protocol.v1.StartSessionRequest
	6,  // 6: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.SessionEvents:input_type -> workflow_plugin_compute_core.protocol.v1.SessionHandle
	8,  // 7: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.ControlSession:input_type -> workflow_plugin_compute_core.protocol.v1.ControlSessionRequest
	1,  // 8: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.Describe:output_type -> workflow_plugin_compute_core.protocol.v1.ProviderCapabilities
	3,  // 9: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.Run:output_type -> workflow_plugin_compute_core.protocol.v1.RunEvent
	6,  // 10: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.StartSession:output_type -> workflow_plugin_compute_core.protocol.v1.SessionHandle
	7,  // 11: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.SessionEvents:output_type -> workflow_plugin_compute_core.protocol.v1.SessionEvent
	9,  // 12: workflow_plugin_compute_core.protocol.v1.RuntimeProviderService.ControlSession:output_type -> workflow_plugin_compute_core.protocol.v1.ControlSessionResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_init() }
func file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_init() {
	if File_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto != nil {
		return
	}
	file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes[3].OneofWrappers = []any{
		(*RunEvent_Stdout)(nil),
		(*RunEvent_Stderr)(nil),
		(*RunEvent_Terminal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDesc), len(file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_goTypes,
		DependencyIndexes: file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_depIdxs,
		MessageInfos:      file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_msgTypes,
	}.Build()
	File_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto = out.File
	file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_goTypes = nil
	file_workflow_plugin_compute_core_protocol_v1_runtime_provider_proto_depIdxs = nil
}
