// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: workflow_plugin_compute_core/protocol/v1/runtime_provider.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeProviderService_Describe_FullMethodName       = "/workflow_plugin_compute_core.protocol.v1.RuntimeProviderService/Describe"
	RuntimeProviderService_Run_FullMethodName            = "/workflow_plugin_compute_core.protocol.v1.RuntimeProviderService/Run"
	RuntimeProviderService_StartSession_FullMethodName   = "/workflow_plugin_compute_core.protocol.v1.RuntimeProviderService/StartSession"
	RuntimeProviderService_SessionEvents_FullMethodName  = "/workflow_plugin_compute_core.protocol.v1.RuntimeProviderService/SessionEvents"
	RuntimeProviderService_ControlSession_FullMethodName = "/workflow_plugin_compute_core.protocol.v1.RuntimeProviderService/ControlSession"
)

// RuntimeProviderServiceClient is the client API for RuntimeProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeProviderService is the gRPC interface that all compute runtime
// providers must implement.
type RuntimeProviderServiceClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*ProviderCapabilities, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*SessionHandle, error)
	SessionEvents(ctx context.Context, in *SessionHandle, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionEvent], error)
	ControlSession(ctx context.Context, in *ControlSessionRequest, opts ...grpc.CallOption) (*ControlSessionResponse, error)
}

type runtimeProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeProviderServiceClient(cc grpc.ClientConnInterface) RuntimeProviderServiceClient {
	return &runtimeProviderServiceClient{cc}
}

func (c *runtimeProviderServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*ProviderCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderCapabilities)
	err := c.cc.Invoke(ctx, RuntimeProviderService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeProviderServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeProviderService_ServiceDesc.Streams[0], RuntimeProviderService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeProviderService_RunClient = grpc.ServerStreamingClient[RunEvent]

func (c *runtimeProviderServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*SessionHandle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionHandle)
	err := c.cc.Invoke(ctx, RuntimeProviderService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeProviderServiceClient) SessionEvents(ctx context.Context, in *SessionHandle, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeProviderService_ServiceDesc.Streams[1], RuntimeProviderService_SessionEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionHandle, SessionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeProviderService_SessionEventsClient = grpc.ServerStreamingClient[SessionEvent]

func (c *runtimeProviderServiceClient) ControlSession(ctx context.Context, in *ControlSessionRequest, opts ...grpc.CallOption) (*ControlSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlSessionResponse)
	err := c.cc.Invoke(ctx, RuntimeProviderService_ControlSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeProviderServiceServer is the server API for RuntimeProviderService service.
// All implementations must embed UnimplementedRuntimeProviderServiceServer
// for forward compatibility.
//
// RuntimeProviderService is the gRPC interface that all compute runtime
// providers must implement.
type RuntimeProviderServiceServer interface {
	Describe(context.Context, *DescribeRequest) (*ProviderCapabilities, error)
	Run(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error
	StartSession(context.Context, *StartSessionRequest) (*SessionHandle, error)
	SessionEvents(*SessionHandle, grpc.ServerStreamingServer[SessionEvent]) error
	ControlSession(context.Context, *ControlSessionRequest) (*ControlSessionResponse, error)
	mustEmbedUnimplementedRuntimeProviderServiceServer()
}

// UnimplementedRuntimeProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeProviderServiceServer struct{}

func (UnimplementedRuntimeProviderServiceServer) Describe(context.Context, *DescribeRequest) (*ProviderCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedRuntimeProviderServiceServer) Run(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedRuntimeProviderServiceServer) StartSession(context.Context, *StartSessionRequest) (*SessionHandle, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedRuntimeProviderServiceServer) SessionEvents(*SessionHandle, grpc.ServerStreamingServer[SessionEvent]) error {
	return status.Error(codes.Unimplemented, "method SessionEvents not implemented")
}
func (UnimplementedRuntimeProviderServiceServer) ControlSession(context.Context, *ControlSessionRequest) (*ControlSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ControlSession not implemented")
}
func (UnimplementedRuntimeProviderServiceServer) mustEmbedUnimplementedRuntimeProviderServiceServer() {
}
func (UnimplementedRuntimeProviderServiceServer) testEmbeddedByValue() {}

// UnsafeRuntimeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeProviderServiceServer will
// result in compilation errors.
type UnsafeRuntimeProviderServiceServer interface {
	mustEmbedUnimplementedRuntimeProviderServiceServer()
}

func RegisterRuntimeProviderServiceServer(s grpc.ServiceRegistrar, srv RuntimeProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeProviderService_ServiceDesc, srv)
}

func _RuntimeProviderService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeProviderServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeProviderService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeProviderServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeProviderService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeProviderServiceServer).Run(m, &grpc.GenericServerStream[RunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeProviderService_RunServer = grpc.ServerStreamingServer[RunEvent]

func _RuntimeProviderService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeProviderServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeProviderService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeProviderServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeProviderService_SessionEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SessionHandle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeProviderServiceServer).SessionEvents(m, &grpc.GenericServerStream[SessionHandle, SessionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeProviderService_SessionEventsServer = grpc.ServerStreamingServer[SessionEvent]

func _RuntimeProviderService_ControlSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeProviderServiceServer).ControlSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeProviderService_ControlSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeProviderServiceServer).ControlSession(ctx, req.(*ControlSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeProviderService_ServiceDesc is the grpc.ServiceDesc for RuntimeProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow_plugin_compute_core.protocol.v1.RuntimeProviderService",
	HandlerType: (*RuntimeProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _RuntimeProviderService_Describe_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _RuntimeProviderService_StartSession_Handler,
		},
		{
			MethodName: "ControlSession",
			Handler:    _RuntimeProviderService_ControlSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _RuntimeProviderService_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SessionEvents",
			Handler:       _RuntimeProviderService_SessionEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workflow_plugin_compute_core/protocol/v1/runtime_provider.proto",
}
